deployment:
  tasks:
    - export APPROOT=/home/cignaadz/public_html/cignumsolutions_ng
    - cd $APPROOT
    - /opt/alt/alt-nodejs20/root/usr/bin/yarn install --frozen-lockfile
    - /opt/alt/alt-nodejs20/root/usr/bin/yarn build
